name: RomM
version: "1.0.6"
slug: romm
description: Beautiful, powerful self-hosted ROM manager and player
url: https://github.com/rommapp/romm
arch:
  - amd64
  - aarch64
  - armv7
init: false
ports:
  8080/tcp: 8998
ports_description:
  8080/tcp: RomM Web Interface
map:
  - share:rw
  - share/romm/library:/romm/library:rw
  - share/romm/resources:/romm/resources:rw
  - share/romm/assets:/romm/assets:rw
  - share/romm/config:/romm/config:rw
options:
  mariadb_host: "core-mariadb"
  mariadb_port: 3306
  mariadb_user: ""
  mariadb_password: ""
  mariadb_database: romm
  igdb_client_id: ""
  igdb_client_secret: ""
  screenscraper_user: ""
  screenscraper_password: ""
schema:
  mariadb_host: str
  mariadb_port: int
  mariadb_user: str
  mariadb_password: str
  mariadb_database: str
  igdb_client_id: str
  igdb_client_secret: str
  screenscraper_user: str
  screenscraper_password: str
